name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: python -m pytest
    
    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Enable APIs
      run: |
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable artifactregistry.googleapis.com
        
    - name: Configure Docker
      run: |
        gcloud auth configure-docker gcr.io
        
    - name: Build & Push Image
      run: |
        docker build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:${{ github.sha }}
        
    - name: Deploy to VM
      run: |
        gcloud compute ssh flask-app-server \
          --zone=us-central1-a \
          --command="
            sudo docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:latest && \
            sudo docker stop flask-app || true && \
            sudo docker rm flask-app || true && \
            sudo docker run -d --name flask-app -p 5000:5000 gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:latest"